### ISSUE TITLE
Positionserkennung ohne GPS

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#1]

**Comment by Fallenstein** [comment]
Genaue Positionserkennung nicht möglich., da kein GPS Sensor vorhanden. Evtl. Möglichkeit über Beschleunigungssensoren bzw Zeit und Geschwindigkeit möglich. Ggf über definierte inkrementelle Flugbewegungen eine zuvor definierte Flugstrecke zurückgelegt werden.
