### ISSUE TITLE
550mAh Akku – Gibt es etwas Größeres?

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#14]

**Comment by Fallenstein** [comment]
700 mA Akku, von Parrot direkt gibts noch einen mit 660

https://www.amazon.de/Parrot-MiniDrone-700mAh-Schnell-Ladeger%C3%A4t/dp/B07G15PKK3/ref=pd_sim_421_5/262-6595924-8975537?_encoding=UTF8&pd_rd_i=B07G15PKK3&pd_rd_r=13e96fa4-efe0-407f-9c99-c3e429191a72&pd_rd_w=W39o6&pd_rd_wg=dDiuX&pf_rd_p=27ff4cf2-95cf-419a-8808-649868aae7d5&pf_rd_r=VVQYMJF7N7HB66ZKN6BJ&psc=1&refRID=VVQYMJF7N7HB66ZKN6BJ

**Comment by manuelberthold** [comment]
Müssen/sollen wir noch etwas besorgen? Den 660 haben wir bereits, oder?

**Comment by manuelberthold** [comment]
@Fallenstein @verenaasslaber Sollen/müssen wir noch etwas besorgen?

**Comment by Fallenstein** [comment]
Neuer Ansatz: Externe Battery wird im hinteren Bereich unterseitig angebracht.  Komplette Batterie Kapazität sollte sich nun auf 1800 mA (+1200mA) erhöhen
Neuen Akkupack bestellt:
https://www.amazon.de/gp/product/B075WVRY5W/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

**Comment by Fallenstein** [comment]
Akku zu schwer. Drohne hebt nicht mehr ab.
