### ISSUE TITLE
Referenzprodukt / Benchmark

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#16]
https://www.flyability.com/elios/

**Comment by MBeyhl** [comment]
Ziel des Benchmarkings: mittels Referenzprodukt die Anforderungen an Drohnen für Einsätze in nahezu unbekanntem Umfeld sowie die technischen Lösungsmöglichkeiten verstehen.

Anforderungen an Drohnen für industrielle Inspektionen vergleichbar 
mit Anforderungen an FRANTS I. --> Flyability als Referenzprodukt gewählt
- Positionserkennung ohne GPS
- Bildaufzeichnung (Full HD Livestream) auch bei staubiger Umgebung möglich
- Kollisionsschutz
- Grösse vergleichbar mit Parrot Mambo
