### ISSUE TITLE
Bei Simulink geht bis jetzt nur Bluetooth Verbindung zur Drohne

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#21]
Überprüfung, ob WLAN Verbindung möglich ist.
Zugehörig zu #35

**Comment by verenaasslaber** [comment]
Eine Verbindung mit WLAN unterstützt das Simulink Hardware Support Package nicht. WLAN wird auch nicht mehr angezeigt sobald man mit bluetooth verbunden ist (was soviel heißt: entweder WLAN und Matlab  oder Bluetooth und Simulink)

**Comment by verenaasslaber** [comment]
Als Ergänzung: das WLAN Signal kommt von der Kamera on top.
