### ISSUE TITLE
Basiswissen object detection:

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#28]
https://de.mathworks.com/help/supportpkg/parrot/ref/color-detection-and-landing-parrot-example.html

**Comment by verenaasslaber** [comment]
Das Beispielprojekte veranschaulicht eine Drohne, die so lange fliegt bis sie ein blaues Objekt auffindet. Dann bleibt sie darüber stehen. Qualität ist beeinträchtigt bei schlechten Lichtverhältnissen. Wäre  aber ein guter Ansatz für unser Projekt. Sowohl für das "autonome" Fahren als auch Objekterkennung
