### ISSUE TITLE
Labyrinth find shortest path reference:

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#3]
https://stackoverflow.com/questions/51043824/how-to-find-shortest-path-in-skeletonized-maze-image

https://github.com/Image-Py/sknw#find-path

**Comment by verenaasslaber** [comment]
![lab_test_1](https://user-images.githubusercontent.com/7521195/73357890-b60faa00-429d-11ea-9954-97a41edfccc4.jpeg)

Shortest Path wird bei einem Test image erkannt. Programmiersprache: Pyhton.
