### ISSUE TITLE
Schemata für Dokumentation und Wiki

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#32]
@simonmuehlbacher

**Comment by MBeyhl** [comment]
Schema am Beispiel Projektarbeit am 18.01.2020:

- Anwesenheit Projektteilnehmer VAS, SMU, MBE, ACF, MBY
  (Bedeutung der Kürzel:  Verena = VAS, Simon = SMU, Manuel = MBE, Arndt = ACF, Moritz = MBY)

- besprochene/bearbeitete Themen
  (Aufbau GitHub, Klärung Anforderungen, Taks für Projektteilnehmer)

- Entscheidungen
  (Simulink als zu verwendendes Programm)

- Administratives
