### ISSUE TITLE
Basiswissen Image Processing

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#34]
https://de.mathworks.com/help/supportpkg/parrot/ref/getting-started-with-parrot-minidrone-vision.html

Moritz

**Comment by MBeyhl** [comment]
Erkenntnisse: 
1) Rumpfkamera liefert Bild 120x160 Pixel im YUV-Format (Y=Helligkeit, U, V=Farben)
   -> dieses Format benötigt weniger Speicherplatz und kann mittels Simulink in RGB-Format 
    (Intensität Rot, Grün, Blau) gewandelt werden
2) Funktionsweise Simulink support package "Code generation template for image processing and control":
- Formatwandlung YUV (Standard) -> RGB einstellen am Ausgang
- nun kann eine Logik eingebaut werden, die die Farbintensitäten miteinander vergleicht. So kann bspw. einen Aktion definiert werden, wenn rote Objekte erkannt werden.
- Oder das Kamerabild kann auch nur ausgegeben werden,
   siehe dazu auch             https://www.youtube.com/watch?v=BzognpCo5HA
