### ISSUE TITLE
Drohne zum fliegen bringen

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#42]
Drohne zum fliegen bringen

**Comment by manuelberthold** [comment]
@verenaasslaber @Fallenstein Ich habe das Ticket nochmal aufgemacht und würde es erst schließen, wenn die Drohne mit Simulink fliegt. Einverstanden?

**Comment by verenaasslaber** [comment]
https://de.mathworks.com/help/aeroblks/quadcopter-project.html
Dieses Simulink Projekt (asbQuadcopterStart) lässt die Drohne mit Matlab fliegen (getestet). Man müsste sich aber noch mehr einlesen um sie dann mit Simulink auch so zu steuern wie man will. 

Meines Erachtens wäre dieses Item erledigt, weil man sie mit Matlab zum Fliegen brachte.

Notiz zu **asbQuadcopterStart**:
Um dieses Projekt zu Starten benötigt man das Hardware Support Package (leider nur in Windows möglich, da die Third Party Libraries in OSX noch nicht 64bit kompatibel sind) für die Parrot Drohne:
https://de.mathworks.com/hardware-support/parrot-minidrones.html
Des Weiteren habe ich bei meiner Matlab Installtion ALLE Programme/Erweiterungen ausgewählt.
Via asbQuadcopterStart in einem LiveScript in Matlab lässt sich dann dieses Example Probjekt starten.
