### ISSUE TITLE
Lego Steine mitbringen

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#54]

**Comment by Fallenstein** [comment]
Mittels Legosteinen (und Heißkleber) die WIFI Kamera der Drohne im 90 grad Winkel nach untern zeigen lassen.

**Comment by Fallenstein** [comment]
.ZIP muss entfernt werden bevor die Datei geöffnet werden.
[Winkel für Kamera.stl.zip](https://github.com/manuelberthold/FRANTS-I./files/4194526/Winkel.fur.Kamera.stl.zip)
