### ISSUE TITLE
Licht mit Parrot Image Conversion erkennen

### ISSUE THREAD

**Issue by manuelberthold** [manuelberthold/FRANTS-I.#55]
http://planetpixelemporium.com/tutorialpages/light.html

https://www.researchgate.net/publication/266646537_Implementation_of_a_Fire_Detection_Algorithm_on_TMS320DM642_DSP_using_MATLABSimulink

Fire Detection: 
https://github.com/wanbin-song/FireDetectionYOLOv2

Smoke Detection:
https://github.com/Duncanswilson/smoke-detection-matting-methods

**Comment by verenaasslaber** [comment]
Funktion via Simulink eingebaut, allerdings konnte noch keine Lichtquelle (Lampe, Feuer) detektiert. werden. Vermutlich liegt es an der geringen Auflösung, als auch über die Übertragungsrate.  Überlegung über Umsteig auf Matlab, da die Auflösung der on top Kamera besser ist und man besser debuggen kann.
