### ISSUE TITLE
Konzeptskizze zum Anbringen der WLAN-Kamera mittels Lego-Steinen

### ISSUE THREAD

**Issue by MBeyhl** [manuelberthold/FRANTS-I.#63]
- Rumpf-Kamera mit geringer Bildqualität (126x120 Pixel, 
  Passbildformat)
-> WLAN-Kamera nötig, diese zeigt standardmässig nur nach 
     vorne
- Parrot Mambo ist Lego kompatibel
- Tragkraft bei etwa 10 g (ohne Flugdauer zu stark 
   einzuschränken)
-> Winkel/Keil aus Legosteinen, damit WLAN-Kamera für Track 1 & 2 genutzt werden kann

**Comment by manuelberthold** [comment]
Wir können auch ein 3D Modell bauen. Weiß nur nicht, ob uns das was bringt für den Bericht.

**Comment by Fallenstein** [comment]
#54

**Comment by Fallenstein** [comment]
> 
> 
> #54

![grafik](https://user-images.githubusercontent.com/59766076/74370048-ba2be380-4dd6-11ea-9cae-c767e5c0b562.png)
